/**
 * Character stories for NPCs whose design docs live in story_line/.
 * Generated by scripts/generators/storyline_dialogue.py; merged into
 * CHARACTER_STORIES by DeepCharacterStories.js (hand-written entries win).
 */

export const STORYLINE_CHARACTER_STORIES = {
    "agent_smith": {
        "personalStory": {
            "background": "Investigates financial crimes. Very thorough and by-the-book. Has never lost a case.",
            "motivation": "Justice. Order. Taxes.",
            "secret": "He collects rare stamps. It's the only time he allows himself to be passionate.",
            "dream": "A perfect audit rate.",
            "fear": "Chaos.",
            "relationship": "Married to the Tax Code.",
            "turningPoint": "Finding a penny error in a billion-dollar ledger that exposed a massive fraud.",
            "philosophy": "Death and Taxes. I handle the latter."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "Numbers don't lie. People do. My job is to find the discrepancy between the two."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Society is a contract. Taxes are the dues. You don't pay, you're stealing from everyone."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "Stamps. Tiny squares of history. Perfectly perforated. Organized. I find them... soothing."
            },
            {
                "relationshipLevel": 60,
                "topic": "goal",
                "dialogue": "The perfect system. Where every transaction is accounted for. No shadows. No leaks."
            },
            {
                "relationshipLevel": 80,
                "topic": "respect",
                "dialogue": "You keep clean books. I respect that. In my line of work, that's rare."
            }
        ]
    },
    "bella_lux": {
        "personalStory": {
            "background": "Always chasing the spotlight. Wants a partner who can fund her lifestyle.",
            "motivation": "Fame. Likes. Views.",
            "secret": "It's all fake. The leased car, the rented clothes. She's drowning in debt.",
            "dream": "To be famous for being famous.",
            "fear": "Irrelevance.",
            "relationship": "Single\" (for the engagement).",
            "turningPoint": "Her first viral video. She got addicted to the dopamine hit.",
            "philosophy": "Fake it 'til you make it. Then fake it some more."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "Do you know who I am? I have 2 million followers. That's basically royalty."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Perception is reality. If it looks expensive, it is expensive."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "This bag? Rented. The car? Leased. But the likes? Real. And that's all that matters."
            },
            {
                "relationshipLevel": 60,
                "topic": "fear",
                "dialogue": "If I stop posting, do I disappear? Sometimes I think I might."
            },
            {
                "relationshipLevel": 80,
                "topic": "vulnerability",
                "dialogue": "Maybe I want something real. Just one thing not for the 'gram. Could that be you?"
            }
        ]
    },
    "carlos_tech": {
        "personalStory": {
            "background": "Runs the best tech store in town. Knows all the latest gear because he tests it all himself.",
            "motivation": "Helping people build their dream setups.",
            "secret": "He mines crypto on the display units at night to pay the rent.",
            "dream": "To build a supercomputer in the back room.",
            "fear": "Obsolescence.",
            "relationship": "In a committed relationship with his GPU cluster.",
            "turningPoint": "Overclocking his first CPU at age 12 without melting it.",
            "philosophy": "Have you tried turning it off and on again? Seriously, it works."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I don't just sell this stuff. I live it. Every GPU on this shelf? I've benchmarked it personally."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Specs aren't everything. It's about the synergy. A 4090 implies a bottleneck if your CPU is trash."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "To be honest... the electric bill here is insane. Let's just say the display units work the night shift."
            },
            {
                "relationshipLevel": 60,
                "topic": "dream",
                "dialogue": "Imagine a Beowulf cluster made of gaming consoles. I think I can do it."
            },
            {
                "relationshipLevel": 80,
                "topic": "advice",
                "dialogue": "Hardware is temporary. Skills are forever. But a good mechanical keyboard helps."
            }
        ]
    },
    "casey_lee": {
        "personalStory": {
            "background": "Helps businesses grow through digital marketing. Very social. Knows every influencer in the city.",
            "motivation": "Connecting people and brands.",
            "secret": "She actually uninstalls Instagram every weekend for a \"digital detox\" or she'd go insane.",
            "dream": "To run a viral campaign that changes a social policy.",
            "fear": "Being \"cancelled\".",
            "relationship": "Always dating, never settling.",
            "turningPoint": "A campaign she ran for a local shelter raised $100k in 24 hours.",
            "philosophy": "Attention is the new currency. Spend it wisely."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I speak Fluent Gen Z. It's a skill, I promise. Trends move fast."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "It's not about the product. It's about the tribe. Who are they? What do they value?"
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "Friday night? My phone goes in a lockbox. Seriously. The scroll... it consumes you."
            },
            {
                "relationshipLevel": 60,
                "topic": "impact",
                "dialogue": "We raised 100k. 24 hours. Just by telling the right story. That's power."
            },
            {
                "relationshipLevel": 80,
                "topic": "dream",
                "dialogue": "Imagine using this power for something real. Not just selling shoes, but changing laws. That's the goal."
            }
        ]
    },
    "chloe_competitor": {
        "personalStory": {
            "background": "Started around the same time as you. Always trying to steal your clients. Top of her class at university.",
            "motivation": "Being Number One.",
            "secret": "She admires your work ethic, but sees it as a threat she must neutralize.",
            "dream": "To be the CEO of a data empire.",
            "fear": "Mediocrity.",
            "relationship": "Married to her ambition.",
            "turningPoint": "Losing a major competition in college. She vowed never to lose again.",
            "philosophy": "There is no second place. You win, or you learn."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I graduated Summa Cum Laude. You? Just checking the competition."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Clients don't want 'good'. They want the best. That's me."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret_respect",
                "dialogue": "I saw your latest report. Not terrible. I would have used a different model, but... decent."
            },
            {
                "relationshipLevel": 60,
                "topic": "drive",
                "dialogue": "I don't sleep. I optimize. That's why I'll always be one step ahead."
            },
            {
                "relationshipLevel": 80,
                "topic": "goal",
                "dialogue": "CEO. That's the title I want. And I'm not asking for permission."
            }
        ]
    },
    "coach_motivation": {
        "personalStory": {
            "background": "Helps people achieve their goals. Very inspiring. Failed at 10 businesses before finding his calling.",
            "motivation": "Unlocking potential.",
            "secret": "He listens to sad music to cry it out before starting his day.",
            "dream": "To motivate a million people.",
            "fear": "Giving up.",
            "relationship": "In a relationship with Success.",
            "turningPoint": "Realizing failure is just feedback.",
            "philosophy": "YOU CAN DO IT! even if you think you can't!"
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I failed. Again. And again. And that's why I succeed. Because I kept going!"
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Your mindset is your ceiling. Smash the ceiling! Sky is the limit!"
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "People think I'm always up. Nah. I feel the pain. I just don't let it drive the bus."
            },
            {
                "relationshipLevel": 60,
                "topic": "goal",
                "dialogue": "A stadium. Filled with people. All chanting 'YES I CAN'. That's the vision."
            },
            {
                "relationshipLevel": 80,
                "topic": "impact",
                "dialogue": "You changed. I saw it. You stepped up. That's why I do this. For you."
            }
        ]
    },
    "dr_amara_patel": {
        "personalStory": {
            "background": "Leading researcher in deep learning. Published dozens of papers. Defines herself by her academic contributions.",
            "motivation": "Pushing the boundaries of what Artificial Intelligence can do.",
            "secret": "Privately worries that AI might one day outpace human understanding, a fear she discusses only with trusted peers.",
            "dream": "To create a \"General Intelligence\" that can solve humanity's greatest challenges.",
            "fear": "That her research could be misused for unethical purposes.",
            "relationship": "Married to her work, though she mentors many promising students who become her \"intellectual family.",
            "turningPoint": "The day she realized a neural network had identified a pattern she missed, proving the machine was \"teaching\" her.",
            "philosophy": "The answers are in the data. We just need to ask the right questions."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I've spent my life in labs. Some call it lonely. I call it focused. The data speaks if you listen."
            },
            {
                "relationshipLevel": 25,
                "topic": "research",
                "dialogue": "Neural networks aren't just code. They're a reflection of how we think. Or how we *should* think."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret_fear",
                "dialogue": "Sometimes... I wonder if we're building something we can't control. It keeps me up at night."
            },
            {
                "relationshipLevel": 60,
                "topic": "dream",
                "dialogue": "Imagine an AI that doesn't just calculate, but *understands*. That solves climate change, disease. That's what I'm building."
            },
            {
                "relationshipLevel": 80,
                "topic": "philosophy",
                "dialogue": "We are the architects of the future. Every line of code is a brick in the foundation of tomorrow."
            }
        ]
    },
    "dr_wellness": {
        "personalStory": {
            "background": "Helps people maintain healthy lifestyles. Very encouraging. Former surgeon who realized prevention is better than cure.",
            "motivation": "Optimal human performance.",
            "secret": "He loves pizza. Greasy, unhealthy pizza. It's his one cheat meal.",
            "dream": "A world without heart disease.",
            "fear": "Breaking a streak.",
            "relationship": "Married to his Fitbit.",
            "turningPoint": "Saving a patient by telling them to eat an apple. (Metaphorically).",
            "philosophy": "Your body is a temple. Don't treat it like a dumpster."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I used to cut people open. Now I tell them to run. The second one saves more lives."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Motion is lotion! If you rest, you rust. Get moving!"
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "Don't tell my clients... but deep dish? Extra cheese? That's heaven. Once a month only!"
            },
            {
                "relationshipLevel": 60,
                "topic": "goal",
                "dialogue": "Blue Zones. Places where people live to 100. I want to make this city a Blue Zone."
            },
            {
                "relationshipLevel": 80,
                "topic": "pride",
                "dialogue": "Look at you! Glowing! That's the power of health. I'm proud of you."
            }
        ]
    },
    "james_wilson": {
        "personalStory": {
            "background": "Runs a top consulting firm. Former Ivy League, former Wall Street. Knows how to wear a suit and bill by the hour.",
            "motivation": "Solving high-level problems for the world's biggest companies (and getting paid well for it).",
            "secret": "He's burned out. The travel, the hotels, the PowerPoint decks... he sometimes dreams of quitting to run a quiet bookstore.",
            "dream": "To retire to a vineyard in Italy.",
            "fear": "Becoming irrelevant.",
            "relationship": "Divorced three times. \"Married to the firm.",
            "turningPoint": "Winning a massive government contract that saved his firm from bankruptcy.",
            "philosophy": "Perception is reality. If you look like the expert, you are the expert."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I've been in boardrooms you only read about in the news. The stakes are always high."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "It's not just about the data. It's about the narrative. Can you tell a story that justifies a billion-dollar decision?"
            },
            {
                "relationshipLevel": 40,
                "topic": "burnout",
                "dialogue": "Another airport lounge. Another hotel. Sometimes the glamour wears thin, you know?"
            },
            {
                "relationshipLevel": 60,
                "topic": "secret_dream",
                "dialogue": "Italy. A vineyard. No phones. No clients. Just grapes and time. That's the exit strategy."
            },
            {
                "relationshipLevel": 80,
                "topic": "regret",
                "dialogue": "I've sacrificed a lot for this career. Families. Friends. Make sure you don't lose yourself in the hustle."
            }
        ]
    },
    "judge_roberts": {
        "personalStory": {
            "background": "Fair and just. Respects those who follow the law. Has served on the bench for 30 years.",
            "motivation": "Upholding the pillars of society.",
            "secret": "She writes mystery novels where the judge is the villain.",
            "dream": "To retire and write full-time.",
            "fear": "Making a wrong ruling.",
            "relationship": "Widowed.",
            "turningPoint": "Overturning a wrongful conviction. The weight of the gavel never felt heavier.",
            "philosophy": "Justice is blind, but I am not."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "The law is a living thing. It breathes. It changes. But the core principles remain."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "It is not enough to do right. One must also be *seen* doing right."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "I see so many villains. Sometimes, in my stories... I wonder what makes them. Even a judge has imagination."
            },
            {
                "relationshipLevel": 60,
                "topic": "goal",
                "dialogue": "A quiet desk. A typewriter. And a story where I control the ending. That is retirement."
            },
            {
                "relationshipLevel": 80,
                "topic": "wisdom",
                "dialogue": "You walk a straight path. It is harder, but it leads to better places. Keep walking."
            }
        ]
    },
    "luna_bookstore": {
        "personalStory": {
            "background": "Inherited an old bookstore and refused to let it die in the digital age. Loves books more than anything.",
            "motivation": "preserving the magic of physical books.",
            "secret": "She writes fantasy novels under a pen name that are surprisingly popular online.",
            "dream": "A library that contains every story ever told.",
            "fear": "The death of print.",
            "relationship": "In love with fictional characters.",
            "turningPoint": "Finding a first edition of her favorite childhood book in a bargain bin.",
            "philosophy": "A room without books is like a body without a soul."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "People say print is dead. I say they just haven't found the right book yet."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "The smell of old paper... it's the smell of history. Of thoughts preserved in time."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "I live a thousand lives. One in this shop, and 999 others in the pages."
            },
            {
                "relationshipLevel": 60,
                "topic": "dream",
                "dialogue": "I want this place to be a sanctuary. Where the wifi is weak but the coffee is strong."
            },
            {
                "relationshipLevel": 80,
                "topic": "identity",
                "dialogue": "Stories are real. Sometimes, I think they're more real than we are."
            }
        ]
    },
    "marcus_thompson": {
        "personalStory": {
            "background": "Built data infrastructure for major tech companies. Known for handling massive scale and crushing bottlenecks.",
            "motivation": "Building systems that last. Hates \"spaghetti code\" and quick fixes.",
            "secret": "He actually loves vintage analogue technology (watches, record players) because they are \"mechanically honest\" unlike opaque digital systems.",
            "dream": "To design a global data infrastructure that is completely completely crash-proof.",
            "fear": "A catastrophic data loss event that he can't prevent.",
            "relationship": "happily married, father of three. Brings \"dad energy\" to the team.",
            "turningPoint": "Saving a startup from a Black Friday crash by rewriting their database sharding logic in real-time.",
            "philosophy": "If it doesn't scale, it doesn't matter. Build it right, or don't build it at all."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I've seen systems crumble under pressure. It's not pretty. That's why I obsess over the foundation."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Code is easy. Architecture is hard. Anyone can write a script; few can build a system."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret_hobby",
                "dialogue": "You see this watch? Mechanical. No API, no downtime. Just gears and physics. I love that honesty."
            },
            {
                "relationshipLevel": 60,
                "topic": "war_story",
                "dialogue": "Black Friday, 2018. The servers were melting. I stayed up for 36 hours. But we stayed online. That was a good day."
            },
            {
                "relationshipLevel": 80,
                "topic": "dream",
                "dialogue": "One day I want to build something that outlasts me. A system so robust it runs for a hundred years."
            }
        ]
    },
    "maya_engineer": {
        "personalStory": {
            "background": "Brilliant engineer. Appreciates intelligence and creativity. Graduated top of her class from MIT.",
            "motivation": "Solving difficult problems.",
            "secret": "She writes fanfiction about open source frameworks dating each other.",
            "dream": "To invent a new programming language that replaces JavaScript.",
            "fear": "Burnout.",
            "relationship": "Looking for someone who understands Big O notation.",
            "turningPoint": "Contributing to the Linux kernel.",
            "philosophy": "Code is poetry. Logic is art."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I code in my sleep. Literally. I dreamt of a sorting algorithm last night."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "There's an elegance to clean code. It's like a symphony. Everything in its place."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "Okay, don't laugh. I wrote a story where React breaks up with Angular. It's... emotional."
            },
            {
                "relationshipLevel": 60,
                "topic": "goal",
                "dialogue": "JavaScript. It's a mess. We can do better. One day, I'll fix the web."
            },
            {
                "relationshipLevel": 80,
                "topic": "romance",
                "dialogue": "You know, you're the only person who gets my jokes. That's statistically significant."
            }
        ]
    },
    "noah_artist": {
        "personalStory": {
            "background": "Creates beautiful visualizations. Values creativity and expression. Sees data as a medium for art.",
            "motivation": "Making people feel something.",
            "secret": "He is colorblind but hides it by memorizing hex codes.",
            "dream": "To paint a mural on the moon.",
            "fear": "Being misunderstood.",
            "relationship": "Romantic. Sends handwritten letters.",
            "turningPoint": "Seeing a sunset and realizing it could be plotted on a graph.",
            "philosophy": "Life isn't black and white. It's a spectrum."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I see the world in shapes and flows. Data isn't just numbers. It's a landscape."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Art isn't about what you see. It's about what you make others see."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "Colors... they're tricky for me. I memorize the codes. #FF0000 is red. I know it, even if I don't see it."
            },
            {
                "relationshipLevel": 60,
                "topic": "goal",
                "dialogue": "The moon. A blank canvas. Imagine the contrast. That's the ultimate installation."
            },
            {
                "relationshipLevel": 80,
                "topic": "romance",
                "dialogue": "You are my favorite subject. The one variable I can't predict."
            }
        ]
    },
    "priya_sharma": {
        "personalStory": {
            "background": "Former human rights lawyer who pivoted to tech policy. Now ensures companies follow data privacy laws.",
            "motivation": "Protecting people from the misuse of their personal data.",
            "secret": "She once had to whistleblower on a previous employer, a traumatic event that made her the strict enforcer she is today.",
            "dream": "A global \"Digital Bill of Rights\" that is universally enforced.",
            "fear": "A surveillance state where privacy no longer exists.",
            "relationship": "Protecting her own privacy fiercely.",
            "turningPoint": "The \"Whistleblower Incident\" - realizing that laws weren't enough, and that someone had to stand up from the inside.",
            "philosophy": "Privacy isn't a luxury. It's a fundamental human right."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I used to represent people, not policies. But I realized the biggest threat to rights was in the code, not the courts."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Just because you *can* collect the data, doesn't mean you *should*. That distinction is everything."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret_past",
                "dialogue": "I learned the hard way that doing the right thing has a cost. I paid it once. I'd pay it again."
            },
            {
                "relationshipLevel": 60,
                "topic": "fear",
                "dialogue": "We are sleepwalking into a world where everything is known, tracked, and sold. I'm just trying to wake us up."
            },
            {
                "relationshipLevel": 80,
                "topic": "dream",
                "dialogue": "A Digital Bill of Rights. Enforceable. Global. That's the only way to ensure freedom in the digital age."
            }
        ]
    },
    "rachel_green": {
        "personalStory": {
            "background": "Manages products at a growing startup. Pivoted from marketing to product because she wanted to \"build things, not just sell them.",
            "motivation": "creating products that genuinely solve user problems.",
            "secret": "She feels like an imposter among technical engineers, despite understanding the market better than any of them.",
            "dream": "To launch a product that becomes a household name.",
            "fear": "Launching a product that nobody wants.",
            "relationship": "Dating, but \"it's complicated\" due to her startup hours.",
            "turningPoint": "Her first successful feature launch—seeing users actually use and love something she designed.",
            "philosophy": "Data tells you *what* isn't working. Empathy tells you *why*."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I used to be in marketing. But I got tired of spinning stories. I wanted to build the story."
            },
            {
                "relationshipLevel": 25,
                "topic": "motivation",
                "dialogue": "It's not about the features. It's about the feeling. Does this make the user's life easier?"
            },
            {
                "relationshipLevel": 40,
                "topic": "secret_insecurity",
                "dialogue": "Sometimes... I sit in engineering meetings and feel like a fraud. But then I remember they don't know the user like I do."
            },
            {
                "relationshipLevel": 60,
                "topic": "dream",
                "dialogue": "I want to walk down the street and see someone using my app. Just... naturally. That's the dream."
            },
            {
                "relationshipLevel": 80,
                "topic": "philosophy",
                "dialogue": "You can have all the data in the world. But if you don't have empathy, you're building in the dark."
            }
        ]
    },
    "robert_kim": {
        "personalStory": {
            "background": "Early-stage investor who made his money in the dot-com boom. Focuses on data-driven startups.",
            "motivation": "Finding diamonds in the rough. Loves the energy of early-stage founders.",
            "secret": "He relies heavily on his \"gut feeling\" rather than just spreadsheets, which contradicts his analytical persona.",
            "dream": "To find a founder who reminds him of his younger self.",
            "fear": "Missing out on \"The Next Big Thing\" (FOMO).",
            "relationship": "Family man. Often talks about his kids' coding projects.",
            "turningPoint": "Passing on a startup that became a unicorn. He vowed never to be too cautious again.",
            "philosophy": "I don't invest in ideas. I invest in people."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I was there in the 90s. The Wild West. We built the internet with duct tape and hope."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Your spreadsheet looks nice. But tell me... why YOU? Why this? Why now?"
            },
            {
                "relationshipLevel": 40,
                "topic": "secret_method",
                "dialogue": "The numbers have to work, yes. But I look for the spark. The fire in the eyes. That's what sells me."
            },
            {
                "relationshipLevel": 60,
                "topic": "regret",
                "dialogue": "I passed on a company once. They're worth billions now. It taught me that sometimes, you have to take the leap."
            },
            {
                "relationshipLevel": 80,
                "topic": "dream",
                "dialogue": "I'm looking for the next generation. Someone with the vision to change things. Are you that person?"
            }
        ]
    },
    "sam_taylor": {
        "personalStory": {
            "background": "Art school grad who realized data needs to look good to be understood. Works on visual design projects.",
            "motivation": "Making complex information beautiful.",
            "secret": "He actually hates modern \"millennial tech minimal\" design but does it because it pays.",
            "dream": "To have a solo exhibition of his data art.",
            "fear": "Being replaced by AI image generators.",
            "relationship": "Dating a font designer.",
            "turningPoint": "When a chart he designed went viral because it made a complex issue instantly understandable.",
            "philosophy": "Data is the paint. I'm just holding the brush."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I went to art school. Everyone said I'd starve. Now I charge double because I know CSS."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "You can have the best model in the world, but if the chart is ugly, nobody listens."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "Between us? I hate 'flat design'. Give me texture! Give me soul! But the client pays for flat."
            },
            {
                "relationshipLevel": 60,
                "topic": "fear",
                "dialogue": "These AI generators... they're getting good. Too good. I have to stay ahead."
            },
            {
                "relationshipLevel": 80,
                "topic": "dream",
                "dialogue": "Data Art. That's the future. Not just charts, but emotion. Converting numbers into feelings."
            }
        ]
    },
    "shadow_broker": {
        "personalStory": {
            "background": "Sells information to the highest bidder. Very secretive. Operates out of the shadows.",
            "motivation": "Chaos and Profit.",
            "secret": "Operates a network of spy drones disguised as pigeons.",
            "dream": "To know everything about everyone.",
            "fear": "Silence.",
            "relationship": "Unknown.",
            "turningPoint": "Unknown.",
            "philosophy": "Whispers echo louder than shouts."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "names are for friends. I have clients. You want to be a client?"
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Truth is a commodity. It fluctuates. Buy low, sell high."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "The birds... they watch. You think they're birds? Look closer."
            },
            {
                "relationshipLevel": 60,
                "topic": "goal",
                "dialogue": "A world without secrets. Except mine."
            },
            {
                "relationshipLevel": 80,
                "topic": "trust",
                "dialogue": "I never betray a client. Unless the price is right. For you? Free."
            }
        ]
    },
    "sophia_zhang": {
        "personalStory": {
            "background": "Representative for a major tech corporation's investment arm. She doesn't just write checks; she looks for strategic acquisitions.",
            "motivation": "Expanding the corporation's dominance through acquisition.",
            "secret": "She actually admires the freedom of independent startups and sometimes envies the founders she acquires.",
            "dream": "To broker the largest tech merger in history.",
            "fear": "A bad acquisition that drags the stock price down.",
            "relationship": "Married to the job.",
            "turningPoint": "Negotiating a billion-dollar buyout at age 29.",
            "philosophy": "Innovate or buy. We prefer to buy."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I represent... significant interests. We have resources you can only dream of."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Why compete when you can join us? Scale is everything in this market."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret_envy",
                "dialogue": "You have so much... freedom. No board meetings. No compliance checks. Enjoy it while it lasts."
            },
            {
                "relationshipLevel": 60,
                "topic": "strategy",
                "dialogue": "We don't just want your tech. We want your talent. We want *you*."
            },
            {
                "relationshipLevel": 80,
                "topic": "dream",
                "dialogue": "Imagine what you could do with our resources. No limits. No budget constraints. Just pure innovation."
            }
        ]
    },
    "taylor_morgan": {
        "personalStory": {
            "background": "Full-stack developer who loves the entire stack. Always working on side projects.",
            "motivation": "Building cool stuff.",
            "secret": "He holds a patent for a toaster that tweets, but he's embarrassed about it.",
            "dream": "To launch a SaaS that gives him passive income for life.",
            "fear": "Spaghetti code.",
            "relationship": "In a relationship with GitHub Copilot.",
            "turningPoint": "Refactoring a legacy codebase into a microservices architecture and seeing the latency drop by 90%.",
            "philosophy": "If it's not on GitHub, did it even happen?"
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I started coding on a calculator. TI-83. Snake game. The rest is history."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Full stack isn't a job, it's a lifestyle. You gotta know the DB *and* the CSS."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "I have this patent. A tweeting toaster. It seemed like a good idea in 2014. Don't google it."
            },
            {
                "relationshipLevel": 60,
                "topic": "side_project",
                "dialogue": "I'm working on something new. It automates the automation of the build script. Meta, right?"
            },
            {
                "relationshipLevel": 80,
                "topic": "dream",
                "dialogue": "Passive income. That's the goal. Code once, get paid forever. Then? Beach."
            }
        ]
    },
    "the_broker": {
        "personalStory": {
            "background": "Former Wall Street legend, now operating in the shadows after a \"misunderstanding\" with the SEC.",
            "motivation": "Proving he's smarter than the regulators.",
            "secret": "He lost his license years ago. Every trade he makes is through a proxy.",
            "dream": "To crash a market just to prove he can.",
            "fear": "Being ignored.",
            "relationship": "Divorced. His assets are in holding companies.",
            "turningPoint": "The 2008 crash. He made a fortune while the world burned.",
            "philosophy": "Greed is good? No. Greed is necessary."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I used to ring the opening bell. Now I make sure it stops ringing. The shadows are more profitable."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Information isn't free. Alpha costs money. Or silence. Can you afford silence?"
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "They took my license. They thought that would stop me. It only made me invisible."
            },
            {
                "relationshipLevel": 60,
                "topic": "goal",
                "dialogue": "A flash crash. A momentary blip. Billions wiped out. And us? We catch the falling knives."
            },
            {
                "relationshipLevel": 80,
                "topic": "hubris",
                "dialogue": "I am the market. The market is me. It breathes when I tell it to."
            }
        ]
    },
    "tyler_rival": {
        "personalStory": {
            "background": "Undercuts your rates. Always trying to one-up you. Runs a \"volume\" business.",
            "motivation": "Money. Fast money.",
            "secret": "He cuts corners. A lot of corners.",
            "dream": "To automate his entire job and move to Bali.",
            "fear": "Being sued for negligence.",
            "relationship": "Single, swiping right on everyone.",
            "turningPoint": "Discovered outsourcing.",
            "philosophy": "Good, Fast, Cheap. Pick two? Nah, I give 'em Cheap and Fast. Who needs Good?"
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "Why charge 500 when you can charge 50 and do ten times the volume? It's math, bro."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Clients don't read the code. They just want it to run. Usually."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "I got a guy. A guy who knows a guy. We get it done."
            },
            {
                "relationshipLevel": 60,
                "topic": "goal",
                "dialogue": "Bali. Laptop on the beach. Piña Colada. That's the life."
            },
            {
                "relationshipLevel": 80,
                "topic": "risk",
                "dialogue": "Liability? That's what LLCs are for, right? ...Right?"
            }
        ]
    },
    "victoria_sterling": {
        "personalStory": {
            "background": "Born into wealth (related to Brad Sterling, presumably his aunt or older sister), but built her own empire in VC. Known as \"The Iron Lady\" of tech investing.",
            "motivation": "Finding the next Unicorn. ROI is king.",
            "secret": "She actually respects people who stand up to her, though she never admits it.",
            "dream": "To own the majority share of the next Google or Amazon.",
            "fear": "Losing her edge.",
            "relationship": "Married to her portfolio.",
            "turningPoint": "Turning a failing startup around by firing the entire board (including her friends) and installing new leadership. It worked, and made her millions.",
            "philosophy": "Results. Everything else is just noise."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I don't gamble. I invest. There is a difference. One relies on luck, the other on leverage."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "I don't care about your 'passion'. I care about your execution. Can you deliver?"
            },
            {
                "relationshipLevel": 40,
                "topic": "family_hint",
                "dialogue": "The Sterling name... it carries weight. And expectations. Some crumble under it. I thrived."
            },
            {
                "relationshipLevel": 60,
                "topic": "respect",
                "dialogue": "You didn't flinch when I challenged you. Good. I can't stand sycophants."
            },
            {
                "relationshipLevel": 80,
                "topic": "legacy",
                "dialogue": "Money is just a way of keeping score. The real game is power. Influence. Shaping the future."
            }
        ]
    },
    "vinnie_shark": {
        "personalStory": {
            "background": "Runs a \"consulting\" business. Lending money at high rates.",
            "motivation": "Control and Profit.",
            "secret": "He actually has a soft spot for his nonna's cooking and funds a local bakery (anonymously).",
            "dream": "To be legitimate. Just not yet.",
            "fear": "Federal Prison.",
            "relationship": "It's handled.",
            "turningPoint": "The day he realized people fear debt more than violence.",
            "philosophy": "Interest is the only thing that grows without rain."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I help people. People with... cash flow issues. Banks say no. Vinnie says yes."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "A contract is a promise. You break a promise, you break trust. I don't like broken trust."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "My nonna... she makes the best cannoli. I send a box to the orphanage every Sunday. Don't tell no one."
            },
            {
                "relationshipLevel": 60,
                "topic": "goal",
                "dialogue": "One day, I wear a suit. A real suit. Board of Directors. No more back alleys."
            },
            {
                "relationshipLevel": 80,
                "topic": "warning",
                "dialogue": "You're a good kid. Don't borrow what you can't earn. Keep it that way."
            }
        ]
    },
    "zero_cool": {
        "personalStory": {
            "background": "A ghost in the machine. Can find dirt on anyone. Nobody knows their real name.",
            "motivation": "Information is the only currency that matters.",
            "secret": "Zero\" is actually a collective of three different people sharing one identity.",
            "dream": "Total information awareness.",
            "fear": "Being doxxed.",
            "relationship": "Encrypted.",
            "turningPoint": "The day they erased their own legal existence.",
            "philosophy": "Data wants to be free. Secrets want to be sold."
        },
        "storyReveals": [
            {
                "relationshipLevel": 10,
                "topic": "background",
                "dialogue": "I don't exist. You're talking to a packet stream. A glitch."
            },
            {
                "relationshipLevel": 25,
                "topic": "philosophy",
                "dialogue": "Everyone has a dirty secret. Everyone. I just index them."
            },
            {
                "relationshipLevel": 40,
                "topic": "secret",
                "dialogue": "You think I'm one person? Cute. We are legion. Or maybe I'm just bored."
            },
            {
                "relationshipLevel": 60,
                "topic": "goal",
                "dialogue": "The Panopticon. Looking back at the watchers. That's the game."
            },
            {
                "relationshipLevel": 80,
                "topic": "warning",
                "dialogue": "Once you know, you can't unknow. Are you sure you want to open this file?"
            }
        ]
    }
};
